on:
  workflow_call:
    inputs:
      file_path:
        description: "file_path"
        required: false
        type: "string"
        default: "."
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

jobs:
  plan:
  container:
    image: alpine/terragrunt:latest
  permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: write
  steps:
    - uses: actions/checkout@v3
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
